// <auto-generated />
using System;
using Mango.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.CouponAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "10OFF",
                            CreatedDate = new DateTime(2024, 2, 21, 20, 47, 24, 340, DateTimeKind.Local).AddTicks(3427),
                            DiscountAmount = 10.0,
                            MinAmount = 20,
                            UpdatedDate = new DateTime(2024, 2, 21, 20, 47, 24, 340, DateTimeKind.Local).AddTicks(3428)
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "20OFF",
                            CreatedDate = new DateTime(2024, 2, 21, 20, 47, 24, 340, DateTimeKind.Local).AddTicks(3467),
                            DiscountAmount = 20.0,
                            MinAmount = 35,
                            UpdatedDate = new DateTime(2024, 2, 21, 20, 47, 24, 340, DateTimeKind.Local).AddTicks(3467)
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "25OFF",
                            CreatedDate = new DateTime(2024, 2, 21, 20, 47, 24, 340, DateTimeKind.Local).AddTicks(3479),
                            DiscountAmount = 40.0,
                            MinAmount = 50,
                            UpdatedDate = new DateTime(2024, 2, 21, 20, 47, 24, 340, DateTimeKind.Local).AddTicks(3479)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
